Release v.1.25.5
matter-labs/onboard pull request #8
Opened 2021-05-07 05:58 UTC by keriat

Generally I've merged initial repo changes.

But alongside list of minor things was done too:

- peer-dependencies inside ```package.json``` were configured right way
- yarn bumped to v.2.* (berry)
- 70% of dependencies had minor updates, so they were upgraded
- local imports I've masked with the ts-path
- tsconfig.json was updated as well
- couple of styles inside Onboard.svelte were dropped since the build process was breaking each time
- provider for the Ledger wallet was totally outdated (discontinued), so I've switched dependency to the tenant package and fixed the connection

Now @popzxc, I'd appreciate small quick review to proceed with publishing and testing it on zkWallet

2021-05-07 06:27 UTC, popzxc approved these changes, later dismissed

2021-05-07 06:27 UTC, popzxc commented on .eslintrc.js
> +}
Nit: Missing newline.

2021-05-07 06:27 UTC, popzxc commented on package.json
> +    "prettier-plugin-svelte": "^2.2.0",
Shouldn't this be in `devDependencies`?

2021-05-07 06:27 UTC, popzxc commented on rollup.config.js
> +}
Nit: Missing newline.

2021-05-07 06:27 UTC, popzxc commented on src/components/Modal.svelte
> +</aside>
Nit: Missing newline (please check everywhere and maybe add it to the lint checks).

2021-05-07 06:27 UTC, popzxc commented on src/elements/Button.svelte
> +      transition: background 150ms ease-in-out;
Nit: Inconsistent alignment.

2021-05-07 10:10 UTC, popzxc requested changes

2021-05-07 10:10 UTC, popzxc commented on LICENSE
> +Copyright (c) 2020 Matter Labs Corp
I don't think we can easily get rid of the copyright. The right statement will be `Copyright (c) 2020 Matter Labs, Blocknative Corp`. Also, Matter Labs is not a corp anyways.

2021-05-07 10:10 UTC, popzxc commented on LICENSE
> +FITNESS FOR A PARTICULAR PURPOSE AND NONINFINGEMENT. IN NO EVENT SHALL THE
The original word was OK, why would you change it?

2021-05-07 10:10 UTC, popzxc commented on package.json
> +    "@ledgerhq/hw-transport-webusb": "^5.51.0",
Why did you make it a peer dependency? It's kinda weird that `hw-app-eth` is a common dependency, and this one is a peer one.

2021-05-07 10:14 UTC, popzxc submitted a review, later dismissed

2021-08-26 19:44 UTC, closed without merging

2021-08-26 19:45 UTC, keriat commented
Abandoned in favor of the source-library.